import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SessionProvider from "./component/SessionProvider";
import "./globals.css";
import { getServerSession } from "next-auth";
import { CounterStoreProvider } from "@/app/providers/app-store-provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CounterStoreProvider>
          <SessionProvider session={session}>{children}</SessionProvider>
        </CounterStoreProvider>
      </body>
    </html>
  );
}
